---
name: "homelab trigger"
description: "Trigger deployment for homelab workflow"
author: "winston0410"
inputs:
  token:
    description: "The GitHub token used to create an authenticated client"
    required: true
  user:
    description: "User for requesting the workflow"
    required: false
    default: "winston0410"
runs:
  using: "composite"
  steps:
    - run: |
        curl -XPOST -u "${{ inputs.user }}:${{inputs.token}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/winston0410/homelab/actions/workflows/deploy.yml/dispatches --data '{"ref": "develop"}'
      shell: bash
