( # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  { config, lib, pkgs, modulesPath, ... }:

  {
    imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

    boot.loader.grub.device = "/dev/sda";

    boot.initrd.availableKernelModules =
      [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/16bb40e9-849f-4063-9fb8-c92c46cf49d6";
      fsType = "ext4";
    };

    swapDevices =
      [{ device = "/dev/disk/by-uuid/1114fbc5-84a2-439e-abc2-eee84f5df7ea"; }];
  })
