---
name: deployment
on:
  push:
    branches: [production]
  pull_request:
    branches: [production]
  workflow_dispatch:
    inputs:
      node:
        description: "Node to build from homelab flake"
        required: false
        default: ""
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
      # TODO Accept build optionally
      - run: nix run github:serokell/deploy-rs -- ${{ github.event.inputs.node }}
